### PR TITLE
feat: make forcerelay-verifier workable in syncing on-chain slots and providing verification ckb transaction

### PR DESCRIPTION
**Pull request by ashuralyk**
I have changed a lot, to talk briefly:
1. optimize the log printing
2. remove the `data_dir` config option from the whole project because it will cache the latest checkpoint which could make an error while bootstrapping
3. add on-chain `tip_slot` check into the syncing procedure because the verifier will keep accepting new headers from rpc even if the relayer stops working, and that will cause mmr storage mismatch

what I do to start a native test:
1. start a native relayer using `ibc-ckb-110` as ckb chain_id to create a light client cell  on ckb running for 4 hours
2. start the verifier to match the `ibc-ckb-110` light client and use the Postman to test rpc `forcerelay_getForcerelayCkbTransaction` with an appropriate transaction hash

@yangby-cryptape please help me review the code so I can deliver it to Acceptance confidently.

### CODE REVIEW

**Review by chaoticlonghair — APPROVED** [review]
I don't understand why requires the parameter `tip_slot`; others part are OK to me.

> and that will cause mmr storage mismatch

A clarification: if the tip of chain is `N`, the tip known by the verifier is `N-M` and the tip stored in CKB chain is `N-M-L`: that's fine.

The API of MMR storage is
https://github.com/synapseweb3/forcerelay-verifier/blob/31f2547be08fe6365ac1b0b6001939077eee41cd/storage/src/prelude.rs#L61-L62

If the tip slot in the verifier is greater than or equal to the max slot stored in CKB chain, then the verifier is able to create MMR proofs for any headers whose slot is less than the max slot stored in CKB chain.

### P.S.

> it will cache the latest checkpoint which could make an error while bootstrapping

I could understand the intent of upstream, and in fact I had the same idea. 
The only difference between my idea and their implement is that I want to cache the data into the database storage.

**Comment by fjchen7** [comment]
Same question here. As far as I understand the verifier is a **simple** relayer but do not append header into light client on CKB. For building mmr it should have the same ability as relayer, and they should be able to sync independently.

**Review by fjchen7 — APPROVED** [review]

**Comment by ashuralyk** [comment]
> I don't understand why requires the parameter `tip_slot`; others part are OK to me.
> 
> > and that will cause mmr storage mismatch
> 
> A clarification: if the tip of chain is `N`, the tip known by the verifier is `N-M` and the tip stored in CKB chain is `N-M-L`: that's fine.
> 
> The API of MMR storage is
> 
> https://github.com/synapseweb3/forcerelay-verifier/blob/31f2547be08fe6365ac1b0b6001939077eee41cd/storage/src/prelude.rs#L61-L62
> 
> If the tip slot in the verifier is greater than or equal to the max slot stored in CKB chain, then the verifier is able to create MMR proofs for any headers whose slot is less than the max slot stored in CKB chain.
> 
> ### P.S.
> > it will cache the latest checkpoint which could make an error while bootstrapping
> 
> I could understand the intent of upstream, and in fact I had the same idea. The only difference between my idea and their implement is that I want to cache the data into the database storage.

I think I have a misunderstanding of mmr storage module features in handling excessive tip slot case, if so as you said, I can remove tip_slot limit from the code.

**Comment by ashuralyk** [comment]
@fjchen7 @yangby-cryptape thanks for both of your considerations on this PR.

**Pull request merged**
